# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Harry_Potterr.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(60, 20, 341, 201))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.calendar.setFont(font)
        self.calendar.setStyleSheet("background:#3c0a00; color:#d4af37; border: 2px solid #4b2e83;")
        self.calendar.setNavigationBarVisible(False)
        self.calendar.setDateEditEnabled(False)
        self.calendar.setObjectName("calendar")
        self.autostart = QtWidgets.QCheckBox(self.centralwidget)
        self.autostart.setGeometry(QtCore.QRect(410, 220, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.autostart.setFont(font)
        self.autostart.setStyleSheet("color:#d4af37;\n"
"background:#3c0a00;")
        self.autostart.setObjectName("autostart")
        self.start_2 = QtWidgets.QPushButton(self.centralwidget)
        self.start_2.setGeometry(QtCore.QRect(240, 220, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.start_2.setFont(font)
        self.start_2.setStyleSheet("background:#4b2e83; color:#d4af37; border: 2px solid #3c0a00;")
        self.start_2.setObjectName("start_2")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(60, 220, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.stop.setFont(font)
        self.stop.setStyleSheet("background:#4b2e83; color:#d4af37; border: 2px solid #3c0a00;")
        self.stop.setObjectName("stop")
        self.video = QVideoWidget(self.centralwidget)
        self.video.setGeometry(QtCore.QRect(410, 20, 331, 201))
        self.video.setStyleSheet("background:#3c0a00; border: 2px solid #d4af37;")
        self.video.setObjectName("video")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setStyleSheet("background:#4b2e83; color:#d4af37;")
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("background:#4b2e83; color:#d4af37;")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Гримоар Чарів"))
        self.autostart.setText(_translate("MainWindow", "      Автостарт ⚡"))
        self.start_2.setText(_translate("MainWindow", "Вперед ✨🪄"))
        self.stop.setText(_translate("MainWindow", "Стояти ⚡"))
from qvideowidget import QVideoWidget
